In [1]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
def plot_fractal(fractal):
    ax = plt.axes()
    for vector in fractal:
        ax.arrow(*vector, lw=3, head_width=0, head_length=0, fc='lightblue', ec='black')
    plt.xlim(-100,100)
    plt.ylim(-100,100)
    plt.axis('equal')

In [3]:
v0 = np.array([5,5,1,0])
endpoint = v0[:2] + v0[2:]

In [42]:
rot_mat

array([[ 0.,  1.],
       [-1.,  0.]])

In [52]:
deg = 3/2*np.pi
rot_mat = np.array([[np.cos(deg),-np.sin(deg)],[np.sin(deg),np.cos(deg)]])

In [53]:
rot_mat

array([[-1.8369702e-16,  1.0000000e+00],
       [-1.0000000e+00, -1.8369702e-16]])

In [54]:
np.array([[0.,1.],[-1.,0.]])

array([[ 0.,  1.],
       [-1.,  0.]])

In [68]:
def fractal(vectors = [], n_recur = 10):
    # 90 deg clockwise
    #deg = 3/2*np.pi
    #deg = 0.4*np.pi
    deg = ((n_recur-32)/(n_recur+1))*np.pi
    rot_mat = np.array([[np.cos(deg),-np.sin(deg)],[np.sin(deg),np.cos(deg)]])
    # rotate and append to end of last vector
    transform = lambda v, v_last: np.r_[v_last[:2] + v_last[2:], np.matmul(rot_mat,v[2:])]
    if n_recur == 0:
        v0 = np.array([5,5,1,0])
        return [v0]
    else:
        # keep all vectors from previous recursion
        vectors = fractal(vectors, n_recur-1)
        new_vectors = vectors.copy()
        for v in vectors:
            new_vectors.append(transform(v, new_vectors[-1]))
        return new_vectors

In [69]:
rot_mat = np.array([[0.,1.],[-1.,0.]])

In [70]:
foo = fractal(n_recur=3)

In [71]:
foo = np.array(foo)

In [72]:
tmp = np.matmul(rot_mat,np.array(foo)[:,2:].T).T

In [73]:
tmp

array([[ 0.00000000e+00, -1.00000000e+00],
       [ 1.00000000e+00,  3.67455938e-15],
       [ 1.22464680e-15, -1.00000000e+00],
       [ 1.00000000e+00,  4.89920618e-15],
       [ 7.07106781e-01,  7.07106781e-01],
       [-7.07106781e-01,  7.07106781e-01],
       [ 7.07106781e-01,  7.07106781e-01],
       [-7.07106781e-01,  7.07106781e-01]])

In [74]:
foo

array([[ 5.00000000e+00,  5.00000000e+00,  1.00000000e+00,
         0.00000000e+00],
       [ 6.00000000e+00,  5.00000000e+00, -3.67455938e-15,
         1.00000000e+00],
       [ 6.00000000e+00,  6.00000000e+00,  1.00000000e+00,
         1.22464680e-15],
       [ 7.00000000e+00,  6.00000000e+00, -4.89920618e-15,
         1.00000000e+00],
       [ 7.00000000e+00,  7.00000000e+00, -7.07106781e-01,
         7.07106781e-01],
       [ 6.29289322e+00,  7.70710678e+00, -7.07106781e-01,
        -7.07106781e-01],
       [ 5.58578644e+00,  7.00000000e+00, -7.07106781e-01,
         7.07106781e-01],
       [ 4.87867966e+00,  7.70710678e+00, -7.07106781e-01,
        -7.07106781e-01]])

In [75]:
np.cumsum(tmp,axis=0) + foo[-1,:2]

array([[4.87867966, 6.70710678],
       [5.87867966, 6.70710678],
       [5.87867966, 5.70710678],
       [6.87867966, 5.70710678],
       [7.58578644, 6.41421356],
       [6.87867966, 7.12132034],
       [7.58578644, 7.82842712],
       [6.87867966, 8.53553391]])

In [76]:
fractal(n_recur=4)

[array([5, 5, 1, 0]),
 array([ 6.00000000e+00,  5.00000000e+00, -3.67455938e-15,  1.00000000e+00]),
 array([6.0000000e+00, 6.0000000e+00, 1.0000000e+00, 1.2246468e-15]),
 array([ 7.00000000e+00,  6.00000000e+00, -4.89920618e-15,  1.00000000e+00]),
 array([ 7.        ,  7.        , -0.70710678,  0.70710678]),
 array([ 6.29289322,  7.70710678, -0.70710678, -0.70710678]),
 array([ 5.58578644,  7.        , -0.70710678,  0.70710678]),
 array([ 4.87867966,  7.70710678, -0.70710678, -0.70710678]),
 array([4.17157288, 7.        , 0.30901699, 0.95105652]),
 array([ 4.48058987,  7.95105652, -0.95105652,  0.30901699]),
 array([3.52953335, 8.26007351, 0.30901699, 0.95105652]),
 array([ 3.83855035,  9.21113003, -0.95105652,  0.30901699]),
 array([ 2.88749383,  9.52014702, -0.89100652, -0.4539905 ]),
 array([ 1.99648731,  9.06615652,  0.4539905 , -0.89100652]),
 array([ 2.45047781,  8.17515   , -0.89100652, -0.4539905 ]),
 array([ 1.55947128,  7.7211595 ,  0.4539905 , -0.89100652])]

In [77]:
%matplotlib qt

In [79]:
plot_fractal(fractal(n_recur=8))
plt.xlim(-100,100)
plt.ylim(-100,100)
#plt.xlim(-50,50)
#plt.ylim(-50,50)

(-100, 100)