### TO DO: add 3d elastic collisions between particles

In [5]:
import numpy as np
import pyro
import torch

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.animation
%matplotlib qt

In [206]:
from scipy.spatial.distance import pdist, squareform

In [198]:
n_timesteps = 20000
n_particles = 5
positions = np.empty((n_timesteps,n_particles,3))
velocities = np.empty((n_timesteps,n_particles,3))

positions[0] = np.random.randn(1,n_particles,3)*3
velocities[0] = np.random.randn(n_particles,3)
velocities[1] = velocities[0]
positions[1] = velocities[1]+positions[0]
rebound = np.ones_like(velocities[0])

for t in range(1,n_timesteps):
    velocities[t] = velocities[t-1]*rebound
    positions[t] = velocities[t]+positions[t-1]
    particle_pairs = list(itertools.combinations(np.arange(n_particles), 2))
    particle_distances = pdist(positions[t])
    particle_collisions = 
    outside_the_box = np.abs(positions[t]+ velocities[t-1]) >= np.ones(3)*10
    rebound = np.ones_like(velocities[t])
    rebound[outside_the_box] = -1

In [201]:
positions[200]

array([[ 7.57295709, -3.16512464,  6.00112969],
       [-1.02202523, -0.26630375, -3.53059135],
       [-6.21666165,  1.8067535 , -8.90380928],
       [-4.15468403, -0.8626017 , -8.12035305],
       [ 6.31860607,  0.05094974, -1.23867607]])

In [211]:
import itertools

In [215]:
particle_pairs = list(itertools.combinations(np.arange(n_particles), 2))

In [216]:
particle_distances = pdist(positions[200])

In [217]:
particle_pairs

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 3),
 (2, 4),
 (3, 4)]

In [218]:
particle_distances

array([13.15790977, 20.90527117, 18.50014737,  8.02068067,  7.75585487,
        5.58883126,  7.69664818,  3.46280415, 14.79763665, 12.56510484])

In [226]:
particle_collisions = [list(pair) for (i,pair) in enumerate(particle_pairs) if particle_distances[i] < 10]

In [227]:
particle_collisions

[[0, 4], [1, 2], [1, 3], [1, 4], [2, 3]]

In [228]:
velocities[200]

array([[ 1.08684486,  0.67302629, -0.04265615],
       [ 0.5572736 , -0.87003684,  0.36672879],
       [ 0.05033073,  0.03372524,  0.51655302],
       [-0.4074473 ,  1.64692067, -0.9667698 ],
       [-0.7096704 ,  0.61301884, -0.75842231]])

In [203]:
np.linalg.norm(positions[200],axis=-1)

array([10.16765709,  3.68517686, 11.00859028,  9.16218394,  6.43907578])

In [229]:
def update_graph(num):
    data=positions[num].T
    graph._offsets3d = (data[0],data[1],data[2])
    title.set_text('3D Test, time={}'.format(num))


fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
#title = ax.set_title('3D Test')
ax.set_xlim(-10,10)
ax.set_ylim(-10,10)
ax.set_zlim(-10,10)

ax.grid(False)

ax.set_xticks([])
ax.set_yticks([])
ax.set_zticks([])

data=particles[0]
graph = ax.scatter(*data.T, s=20)

ani = matplotlib.animation.FuncAnimation(fig, update_graph, n_timesteps, 
                               interval=50, blit=False)