In [7]:
import numpy as np
from sklearn.metrics import accuracy_score

In [15]:
N = 10000
true = np.random.choice(np.arange(3),size=N)
guessing = np.random.choice(np.arange(3),size=N)
one_class = np.random.choice(np.arange(3),size=N, p=np.array([0.6,0.2,0.2]))
one_class2 = np.random.choice(np.arange(3),size=N, p=np.array([1,0,0]))

In [16]:
true

array([1, 2, 1, ..., 0, 2, 1])

In [17]:
guessing

array([2, 0, 2, ..., 0, 0, 1])

In [18]:
one_class

array([0, 0, 0, ..., 2, 0, 2])

In [19]:
accuracy_score(true, guessing)

0.337

In [21]:
accuracy_score(true, one_class2)

0.3341